import type { TunnelSpec } from '@/types/tunnel'

export const DEMO_TUNNELS: TunnelSpec[] = [
  {
    id: 'demo-1',
    name: 'prod-database',
    owner: 'devops-team',
    type: 'local',
    hops: [
      {
        host: 'bastion.prod.example.com',
        port: 22,
        user: 'deploy',
        auth_method: 'key',
      },
    ],
    localPort: 5432,
    remoteHost: 'postgres.internal.prod.example.com',
    remotePort: 5432,
    autoReconnect: true,
    keepAlive: 30,
    maxRetries: 5,
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(), // 3 days ago
    updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 mins ago
    lastConnected: new Date(Date.now() - 1000 * 60 * 5).toISOString(), // 5 mins ago
  },
  {
    id: 'demo-2',
    name: 'staging-redis',
    owner: 'backend-team',
    type: 'local',
    hops: [
      {
        host: 'jump.staging.example.com',
        port: 22,
        user: 'ubuntu',
        auth_method: 'key',
      },
    ],
    localPort: 6379,
    remoteHost: 'redis.staging.internal',
    remotePort: 6379,
    autoReconnect: true,
    keepAlive: 60,
    maxRetries: 3,
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    lastConnected: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  },
  {
    id: 'demo-3',
    name: 'socks-proxy',
    owner: 'security-team',
    type: 'dynamic',
    hops: [
      {
        host: 'proxy.corporate.example.com',
        port: 22,
        user: 'sysadmin',
        auth_method: 'key',
      },
    ],
    localPort: 1080,
    remoteHost: '',
    remotePort: 0,
    autoReconnect: true,
    keepAlive: 45,
    maxRetries: 10,
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(), // 12 hours ago
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    lastConnected: new Date(Date.now() - 1000 * 30).toISOString(),
  },
  {
    id: 'demo-4',
    name: 'api-gateway',
    owner: 'platform-team',
    type: 'local',
    hops: [
      {
        host: 'bastion-1.prod.example.com',
        port: 22,
        user: 'sre',
        auth_method: 'key',
      },
      {
        host: 'bastion-2.prod.internal',
        port: 22,
        user: 'sre',
        auth_method: 'key',
      },
    ],
    localPort: 8080,
    remoteHost: 'api.prod.internal',
    remotePort: 443,
    autoReconnect: true,
    keepAlive: 30,
    maxRetries: 5,
    status: 'connecting',
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(), // 5 mins ago
    updatedAt: new Date(Date.now() - 1000 * 30).toISOString(),
  },
  {
    id: 'demo-5',
    name: 'dev-elasticsearch',
    owner: 'analytics-team',
    type: 'local',
    hops: [
      {
        host: 'dev-jump.example.com',
        port: 2222,
        user: 'developer',
        auth_method: 'key',
      },
    ],
    localPort: 9200,
    remoteHost: 'es-cluster.dev.internal',
    remotePort: 9200,
    autoReconnect: false,
    keepAlive: 30,
    maxRetries: 2,
    status: 'disconnected',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(), // 2 days ago
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    errorMessage: 'Connection timeout after 30s',
  },
  {
    id: 'demo-6',
    name: 'mongodb-replica',
    owner: 'data-team',
    type: 'local',
    hops: [
      {
        host: 'bastion.data.example.com',
        port: 22,
        user: 'datadmin',
        auth_method: 'key',
      },
    ],
    localPort: 27017,
    remoteHost: 'mongo-primary.internal',
    remotePort: 27017,
    autoReconnect: true,
    keepAlive: 60,
    maxRetries: 5,
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(), // 1 week ago
    updatedAt: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
    lastConnected: new Date(Date.now() - 1000 * 60).toISOString(),
  },
  {
    id: 'demo-7',
    name: 'jenkins-ci',
    owner: 'devops-team',
    type: 'local',
    hops: [
      {
        host: 'ci-gateway.example.com',
        port: 22,
        user: 'jenkins',
        auth_method: 'key',
      },
    ],
    localPort: 8888,
    remoteHost: 'jenkins.internal',
    remotePort: 8080,
    autoReconnect: true,
    keepAlive: 30,
    maxRetries: 3,
    status: 'failed',
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    errorMessage: 'Authentication failed: invalid SSH key',
  },
  {
    id: 'demo-8',
    name: 'grafana-metrics',
    owner: 'observability-team',
    type: 'local',
    hops: [
      {
        host: 'monitoring.example.com',
        port: 22,
        user: 'grafana',
        auth_method: 'key',
      },
    ],
    localPort: 3000,
    remoteHost: 'grafana.internal',
    remotePort: 3000,
    autoReconnect: true,
    keepAlive: 45,
    maxRetries: 5,
    status: 'active',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    lastConnected: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
  },
]
